-- Filename: DB_Skill.lua
-- Author: auto-created by XmlToScript tool.
-- Function: it`s auto-created by XmlToScript tool.
--ExcelVBA output tools start flag
module("DB_ArtifactConfig", package.seeall)
--{id,名称id,描述id,图标id,品质,品级,真气值,属性条数,基本属性1,基本属性2,基本属性3,基本属性4,基本属性5,基本属性6,基本属性7,基本属性8,基本属性1成长,基本属性2成长,基本属性3成长,基本属性4成长,基本属性5成长,基本属性6成长,基本属性7成长,基本属性8成长,类型,}

ArtifactConfig = {
	[1] = {["ID"] = 1,["Name"] = 4201,["Description"] = 4301,["IconID"] = 2901,["Quality"] = 1,["Level"] = 5,["Breaknumber"] = 25,["number"] = 1,["InitHP"] = 1800,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 900,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 1,},
	[2] = {["ID"] = 2,["Name"] = 4202,["Description"] = 4302,["IconID"] = 2902,["Quality"] = 1,["Level"] = 4,["Breaknumber"] = 25,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 80,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 40,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 3,},
	[3] = {["ID"] = 3,["Name"] = 4203,["Description"] = 4303,["IconID"] = 2903,["Quality"] = 1,["Level"] = 3,["Breaknumber"] = 25,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 80,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 40,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 4,},
	[4] = {["ID"] = 4,["Name"] = 4204,["Description"] = 4304,["IconID"] = 2904,["Quality"] = 1,["Level"] = 2,["Breaknumber"] = 25,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 80,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 40,["InitTenacityleveladd"] = 0,["Type"] = 7,},
	[5] = {["ID"] = 5,["Name"] = 4205,["Description"] = 4305,["IconID"] = 2905,["Quality"] = 1,["Level"] = 1,["Breaknumber"] = 25,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 80,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 40,["Type"] = 8,},
	[11] = {["ID"] = 11,["Name"] = 4206,["Description"] = 4306,["IconID"] = 2906,["Quality"] = 2,["Level"] = 15,["Breaknumber"] = 50,["number"] = 1,["InitHP"] = 3600,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 1800,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 1,},
	[12] = {["ID"] = 12,["Name"] = 4207,["Description"] = 4307,["IconID"] = 2907,["Quality"] = 2,["Level"] = 18,["Breaknumber"] = 50,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 160,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 80,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 2,},
	[13] = {["ID"] = 13,["Name"] = 4208,["Description"] = 4308,["IconID"] = 2908,["Quality"] = 2,["Level"] = 14,["Breaknumber"] = 50,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 160,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 80,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 3,},
	[14] = {["ID"] = 14,["Name"] = 4209,["Description"] = 4309,["IconID"] = 2909,["Quality"] = 2,["Level"] = 13,["Breaknumber"] = 50,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 160,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 80,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 4,},
	[15] = {["ID"] = 15,["Name"] = 4210,["Description"] = 4310,["IconID"] = 2910,["Quality"] = 2,["Level"] = 17,["Breaknumber"] = 50,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 160,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 80,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 5,},
	[16] = {["ID"] = 16,["Name"] = 4211,["Description"] = 4311,["IconID"] = 2911,["Quality"] = 2,["Level"] = 16,["Breaknumber"] = 50,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 160,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 80,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 6,},
	[17] = {["ID"] = 17,["Name"] = 4212,["Description"] = 4312,["IconID"] = 2912,["Quality"] = 2,["Level"] = 12,["Breaknumber"] = 50,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 160,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 80,["InitTenacityleveladd"] = 0,["Type"] = 7,},
	[18] = {["ID"] = 18,["Name"] = 4213,["Description"] = 4313,["IconID"] = 2913,["Quality"] = 2,["Level"] = 11,["Breaknumber"] = 50,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 160,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 80,["Type"] = 8,},
	[21] = {["ID"] = 21,["Name"] = 4214,["Description"] = 4314,["IconID"] = 2914,["Quality"] = 3,["Level"] = 25,["Breaknumber"] = 100,["number"] = 1,["InitHP"] = 7200,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 3600,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 1,},
	[22] = {["ID"] = 22,["Name"] = 4215,["Description"] = 4315,["IconID"] = 2915,["Quality"] = 3,["Level"] = 28,["Breaknumber"] = 100,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 320,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 160,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 2,},
	[23] = {["ID"] = 23,["Name"] = 4216,["Description"] = 4316,["IconID"] = 2916,["Quality"] = 3,["Level"] = 24,["Breaknumber"] = 100,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 320,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 160,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 3,},
	[24] = {["ID"] = 24,["Name"] = 4217,["Description"] = 4317,["IconID"] = 2917,["Quality"] = 3,["Level"] = 23,["Breaknumber"] = 100,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 320,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 160,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 4,},
	[25] = {["ID"] = 25,["Name"] = 4218,["Description"] = 4318,["IconID"] = 2918,["Quality"] = 3,["Level"] = 27,["Breaknumber"] = 100,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 320,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 160,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 5,},
	[26] = {["ID"] = 26,["Name"] = 4219,["Description"] = 4319,["IconID"] = 2919,["Quality"] = 3,["Level"] = 26,["Breaknumber"] = 100,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 320,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 160,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 6,},
	[27] = {["ID"] = 27,["Name"] = 4220,["Description"] = 4320,["IconID"] = 2920,["Quality"] = 3,["Level"] = 22,["Breaknumber"] = 100,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 320,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 160,["InitTenacityleveladd"] = 0,["Type"] = 7,},
	[28] = {["ID"] = 28,["Name"] = 4221,["Description"] = 4321,["IconID"] = 2921,["Quality"] = 3,["Level"] = 21,["Breaknumber"] = 100,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 320,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 160,["Type"] = 8,},
	[31] = {["ID"] = 31,["Name"] = 4222,["Description"] = 4322,["IconID"] = 2922,["Quality"] = 4,["Level"] = 35,["Breaknumber"] = 200,["number"] = 1,["InitHP"] = 10800,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 5400,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 1,},
	[32] = {["ID"] = 32,["Name"] = 4223,["Description"] = 4323,["IconID"] = 2923,["Quality"] = 4,["Level"] = 38,["Breaknumber"] = 200,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 480,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 240,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 2,},
	[33] = {["ID"] = 33,["Name"] = 4224,["Description"] = 4324,["IconID"] = 2924,["Quality"] = 4,["Level"] = 34,["Breaknumber"] = 200,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 480,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 240,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 3,},
	[34] = {["ID"] = 34,["Name"] = 4225,["Description"] = 4325,["IconID"] = 2925,["Quality"] = 4,["Level"] = 33,["Breaknumber"] = 200,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 480,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 240,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 4,},
	[35] = {["ID"] = 35,["Name"] = 4226,["Description"] = 4326,["IconID"] = 2926,["Quality"] = 4,["Level"] = 37,["Breaknumber"] = 200,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 480,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 240,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 5,},
	[36] = {["ID"] = 36,["Name"] = 4227,["Description"] = 4327,["IconID"] = 2927,["Quality"] = 4,["Level"] = 36,["Breaknumber"] = 200,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 480,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 240,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 6,},
	[37] = {["ID"] = 37,["Name"] = 4228,["Description"] = 4328,["IconID"] = 2928,["Quality"] = 4,["Level"] = 32,["Breaknumber"] = 200,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 480,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 240,["InitTenacityleveladd"] = 0,["Type"] = 7,},
	[38] = {["ID"] = 38,["Name"] = 4229,["Description"] = 4329,["IconID"] = 2929,["Quality"] = 4,["Level"] = 31,["Breaknumber"] = 200,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 480,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 240,["Type"] = 8,},
	[39] = {["ID"] = 39,["Name"] = 4230,["Description"] = 4330,["IconID"] = 2930,["Quality"] = 4,["Level"] = 39,["Breaknumber"] = 200,["number"] = 2,["InitHP"] = 5400,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 240,["InitHit"] = 0,},
	[40] = {["ID"] = 40,["Name"] = 4231,["Description"] = 4331,["IconID"] = 2931,["Quality"] = 4,["Level"] = 42,["Breaknumber"] = 200,["number"] = 2,["InitHP"] = 0,["InitPhyAttack"] = 240,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 240,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 120,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 120,["InitTenacityleveladd"] = 0,["Type"] = 10,},
	[41] = {["ID"] = 41,["Name"] = 4232,["Description"] = 4332,["IconID"] = 2932,["Quality"] = 4,["Level"] = 41,["Breaknumber"] = 200,["number"] = 2,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 240,["InitArmor"] = 0,["InitHit"] = 240,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 120,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 120,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 11,},
	[42] = {["ID"] = 42,["Name"] = 4233,["Description"] = 4333,["IconID"] = 2933,["Quality"] = 4,["Level"] = 40,["Breaknumber"] = 200,["number"] = 2,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 240,["InitCrit"] = 0,["InitTenacity"] = 240,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 120,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 120,["Type"] = 12,},
	[49] = {["ID"] = 49,["Name"] = 4234,["Description"] = 4334,["IconID"] = 2900,["Quality"] = 0,["Level"] = 0,["Breaknumber"] = 500,["number"] = 0,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 0,},
	[51] = {["ID"] = 51,["Name"] = 4235,["Description"] = 4335,["IconID"] = 2934,["Quality"] = 5,["Level"] = 55,["Breaknumber"] = 400,["number"] = 1,["InitHP"] = 16200,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 7200,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 1,},
	[52] = {["ID"] = 52,["Name"] = 4236,["Description"] = 4336,["IconID"] = 2935,["Quality"] = 5,["Level"] = 58,["Breaknumber"] = 400,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 720,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 320,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 2,},
	[53] = {["ID"] = 53,["Name"] = 4237,["Description"] = 4337,["IconID"] = 2936,["Quality"] = 5,["Level"] = 54,["Breaknumber"] = 400,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 720,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 320,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 3,},
	[54] = {["ID"] = 54,["Name"] = 4238,["Description"] = 4338,["IconID"] = 2937,["Quality"] = 5,["Level"] = 53,["Breaknumber"] = 400,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 720,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 320,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 4,},
	[55] = {["ID"] = 55,["Name"] = 4239,["Description"] = 4339,["IconID"] = 2938,["Quality"] = 5,["Level"] = 57,["Breaknumber"] = 400,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 720,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 320,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 5,},
	[56] = {["ID"] = 56,["Name"] = 4240,["Description"] = 4340,["IconID"] = 2939,["Quality"] = 5,["Level"] = 56,["Breaknumber"] = 400,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 720,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 320,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 6,},
	[57] = {["ID"] = 57,["Name"] = 4241,["Description"] = 4341,["IconID"] = 2940,["Quality"] = 5,["Level"] = 52,["Breaknumber"] = 400,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 720,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 320,["InitTenacityleveladd"] = 0,["Type"] = 7,},
	[58] = {["ID"] = 58,["Name"] = 4242,["Description"] = 4342,["IconID"] = 2941,["Quality"] = 5,["Level"] = 51,["Breaknumber"] = 400,["number"] = 1,["InitHP"] = 0,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 720,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 320,["Type"] = 8,},
	[59] = {["ID"] = 59,["Name"] = 4243,["Description"] = 4343,["IconID"] = 2942,["Quality"] = 5,["Level"] = 61,["Breaknumber"] = 400,["number"] = 2,["InitHP"] = 8100,["InitPhyAttack"] = 360,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 3600,["InitPhyAttackleveladd"] = 160,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 13,},
	[60] = {["ID"] = 60,["Name"] = 4244,["Description"] = 4344,["IconID"] = 2943,["Quality"] = 5,["Level"] = 60,["Breaknumber"] = 400,["number"] = 2,["InitHP"] = 8100,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 360,["InitDodge"] = 0,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 3600,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 160,["InitDodgeleveladd"] = 0,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 14,},
	[61] = {["ID"] = 61,["Name"] = 4245,["Description"] = 4345,["IconID"] = 2944,["Quality"] = 5,["Level"] = 59,["Breaknumber"] = 400,["number"] = 2,["InitHP"] = 8100,["InitPhyAttack"] = 0,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 0,["InitDodge"] = 360,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 3600,["InitPhyAttackleveladd"] = 0,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 0,["InitDodgeleveladd"] = 160,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 15,},
	[62] = {["ID"] = 62,["Name"] = 4246,["Description"] = 4346,["IconID"] = 2945,["Quality"] = 5,["Level"] = 62,["Breaknumber"] = 400,["number"] = 3,["InitHP"] = 0,["InitPhyAttack"] = 270,["InitArmorPene"] = 0,["InitArmor"] = 0,["InitHit"] = 270,["InitDodge"] = 270,["InitCrit"] = 0,["InitTenacity"] = 0,["InitHPleveladd"] = 0,["InitPhyAttackleveladd"] = 120,["InitArmorPeneleveladd"] = 0,["InitArmorleveladd"] = 0,["InitHitleveladd"] = 120,["InitDodgeleveladd"] = 120,["InitCritleveladd"] = 0,["InitTenacityleveladd"] = 0,["Type"] = 16,},
}

function getDataById(key_id)
    local id_data = ArtifactConfig[key_id]

    return id_data
end

function getArrDataByField(fieldName, fieldValue)
    local arrData = {}
    for k, v in pairs(ArtifactConfig) do
        if v[fieldName] == fieldValue then
            arrData[#arrData+1] = v
        end
    end

    return arrData
end

function release()
    _G["DB_ArtifactConfig"] = nil
    package.loaded["DB_ArtifactConfig"] = nil
    package.loaded["DBSystem/DB_ArtifactConfig"] = nil
end
--ExcelVBA output tools end flag